### ISSUE TITLE
missing: `FreeCADGui.PySideUic`

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [ostr00000/freecad-stubs#14]
https://github.com/FreeCAD/FreeCAD/blob/759930e3aab711355d2f0895f641a8657897af48/src/Gui/Application.cpp#L426
```cpp
        PyObject* module = PyDict_GetItemString(modules, "FreeCADGui");
```
https://github.com/FreeCAD/FreeCAD/blob/759930e3aab711355d2f0895f641a8657897af48/src/Gui/Application.cpp#L450
```cpp
        PyModule_AddObject(module, "PySideUic", Base::Interpreter().addModule(new PySideUicModule));
```

**Comment by ostr00000** [comment]
Should be fixed in https://github.com/ostr00000/freecad-stubs/commit/7ed580b3f67653a96bb6f5ff85e3ab9efa1958dd
